Fix bugs and add info
intel/libxcam pull request #809
Opened 2022-09-05 02:43 UTC by zihengchang

* Allow getting device parameters from ffmpeg pipeline
    * Add unit test with frame mode multi, supplementary info
    * Fix code conflict in hardware decoding mode

2022-09-06 10:06 UTC, zongwave requested changes

2022-09-06 10:06 UTC, zongwave commented on modules/gles/gl_stitcher.cpp
> +        fwrite (param->out_buf->map(), 7680 * 3840 * 3 / 2, 1, fbo_file);
don't hardcode image resolution.

2022-09-06 10:06 UTC, zongwave commented on modules/gles/gl_stitcher.cpp
> +    ret = _impl->init_config (param);
can you guarantee init_config only be called once?

2022-09-06 10:06 UTC, zongwave commented on xcore/base/xcam_buffer.h
> +    int                   hw_codec;
can you use mem_type instead?
typedef enum {
    XCAM_MEM_TYPE_CPU,
    XCAM_MEM_TYPE_GPU,
    XCAM_MEM_TYPE_PRIVATE = 0x8000,
    XCAM_MEM_TYPE_PRIVATE_BO,
} XCamMemType;

2022-09-07 02:48 UTC, zihengchang commented on modules/gles/gl_dma_buffer_handler.cpp
> +#define DUMP_TEST 0
Conditional compilation is more convenient if TEST_DEBUG is defined
https://github.com/intel/libxcam/blob/43d2aadcdc82da0a784c08f425f78bd37d6612f7/modules/gles/gl_dma_buffer_handler.cpp#L168

2022-10-20 06:05 UTC, zongwave requested changes

2022-10-20 06:05 UTC, zongwave commented on modules/gles/gl_stitcher.cpp
> +        ret = _impl->init_dmabuf (param);
init_dmabuf_handler

2022-10-20 06:05 UTC, zongwave commented on tests/test-surround-view.cpp
> -        file_name, 256, "%s-%dx%d.%05d.%s.yuv",
to line 85: 
inside in function tex->dump_texture_image (file_name);
modify fopen (..., 'wb+')

2023-05-18 13:34 UTC, uartie commented
stale, no activity for 7 months. closing.  feel free to reopen when issues resolved.

2023-05-18 13:34 UTC, closed without merging