dnn: update dnn module to openvino version 2023/0
intel/libxcam pull request #830
Opened 2023-07-05 13:49 UTC by alimt1992

dnn: update dnn module to openvino version 2023/0

    *git clone https://github.com/openvinotoolkit/openvino.git
    *git checkout -b releases/2023/0 origin/releases/2023/0
    *export OPENVINO_IE_LIBS_PATH=/openvino/bin/intel64/Release
    *export OPENVINO_IE_INC_PATH=/usr/local/runtime/include/

2023-07-31 07:34 UTC, zongwave commented
OpenVino 2023 released a Linux distribution package at https://docs.openvino.ai/2023.0/openvino_docs_install_guides_installing_openvino_from_archive_linux.html
With this release user can install & setup OpenVino environment by running a script “source /opt/intel/openvino_2023/setupvars.sh”, the library and include path also can be exported by openvino.pc file.

automake can use pkg-config tool to get OpenVino path:
$ pkg-config --cflags openvino
-DTBB_PREVIEW_WAITING_FOR_WORKERS=1 -DIE_THREAD=IE_THREAD_TBB -DOV_THREAD=OV_THREAD_TBB -I/opt/intel/openvino_2023.0.1/runtime/lib/intel64/pkgconfig/../../../..//runtime/include/ie -I/opt/intel/openvino_2023.0.1/runtime/lib/intel64/pkgconfig/../../../..//runtime/include


$ pkg-config --libs openvino
-L/opt/intel/openvino_2023.0.1/runtime/lib/intel64/pkgconfig/../../../..//runtime/lib/intel64 -lopenvino_onnx_frontend -lopenvino_paddle_frontend -lopenvino_pytorch_frontend -lopenvino_tensorflow_frontend -lopenvino_tensorflow_lite_frontend -lopenvino_c -lopenvino -ltbb -lpugixml

 
I think we can remove the compiling flags “OPENVINO_IE_LIBS_PATH” & “OPENVINO_IE_INC_PATH”.

2023-07-31 23:02 UTC, alimt1992 commented
> OpenVino 2023 released a Linux distribution package at https://docs.openvino.ai/2023.0/openvino_docs_install_guides_installing_openvino_from_archive_linux.html With this release user can install & setup OpenVino environment by running a script “source /opt/intel/openvino_2023/setupvars.sh”, the library and include path also can be exported by openvino.pc file.
> 
> automake can use pkg-config tool to get OpenVino path: $ pkg-config --cflags openvino -DTBB_PREVIEW_WAITING_FOR_WORKERS=1 -DIE_THREAD=IE_THREAD_TBB -DOV_THREAD=OV_THREAD_TBB -I/opt/intel/openvino_2023.0.1/runtime/lib/intel64/pkgconfig/../../../..//runtime/include/ie -I/opt/intel/openvino_2023.0.1/runtime/lib/intel64/pkgconfig/../../../..//runtime/include
> 
> $ pkg-config --libs openvino -L/opt/intel/openvino_2023.0.1/runtime/lib/intel64/pkgconfig/../../../..//runtime/lib/intel64 -lopenvino_onnx_frontend -lopenvino_paddle_frontend -lopenvino_pytorch_frontend -lopenvino_tensorflow_frontend -lopenvino_tensorflow_lite_frontend -lopenvino_c -lopenvino -ltbb -lpugixml
> 
> I think we can remove the compiling flags “OPENVINO_IE_LIBS_PATH” & “OPENVINO_IE_INC_PATH”.

changed dnn module Makefile.am accordingly. In order to access format_reader include and libs, an environment variable, "OPENVINO_EXTRAS_PATH" has been added.

2023-08-01 06:51 UTC, zongwave requested changes

2023-08-01 06:51 UTC, zongwave commented on modules/dnn/inference/Makefile.am
Please also remove $(OPENVINO_IE_LIBS_PATH) at line 50
libxcam_dnn_la_LDFLAGS = \
    $(XCAM_LT_LDFLAGS)   \
    -Wl,-rpath,$(OPENVINO_IE_LIBS_PATH) \
    $(NULL)

2023-08-01 06:51 UTC, zongwave commented on modules/dnn/inference/Makefile.am
> +    -lie_samples_utils \
this library seems no used, try to remove it.

2023-08-01 06:51 UTC, zongwave commented on modules/dnn/inference/Makefile.am
> +    -lopenvino \
try to replace these -lopenvinoxxx by $(LIBOPENVINO_LIBS) generated by pkgconfig.

2023-08-01 06:51 UTC, zongwave commented on modules/dnn/inference/Makefile.am
> +    -L$(OPENVINO_EXTRAS_PATH)/bin/intel64/Release \
move this line above -lformat_reader

2023-08-01 08:37 UTC, zongwave requested changes

2023-08-01 08:37 UTC, zongwave commented on README.md
> +        source /usr/setupvars.sh
shell "setupvars.sh" are commonly used for many 3rd party libraries. put this openvino speicified shell under folder /usr might be not very friendly.

2023-08-01 08:37 UTC, zongwave commented on README.md
> +        source /usr/setupvars.sh
same as line 91, for example:
/opt/intel/openvino_2023/setupvars.sh
/opt/intel/oneapi/setupvars.sh
... ...

2023-08-07 05:25 UTC, zongwave requested changes

2023-08-07 09:04 UTC, zongwave approved these changes

2023-08-07 09:04 UTC, merged